[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge = "FuRZXPZZEhdtgtNw2m5aHgmjRxHJEExv688maA3sGb8p"
lock_and_unlock = "965BxygGCearNwucNBTsnhNVTa6SGhKtwNoopbtGQjQp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
